# -*- coding: utf-8 -*-
"""Sales Trend Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sPC6kI8qbUEn6ktomm6F1X-wg06edCP
"""

!pip install pandas

import pandas as pd
import sqlite3

from google.colab import files
uploaded = files.upload()

# Load CSV
df = pd.read_csv("online_sales_large.csv")

# Create in-memory SQLite database
conn = sqlite3.connect(":memory:")

# Save DataFrame as a SQL table
df.to_sql("online_sales_large", conn, index=False, if_exists="replace")

query = """
SELECT
    STRFTIME('%Y', order_date) AS year,
    STRFTIME('%m', order_date) AS month,
    SUM(amount) AS monthly_revenue,
    COUNT(DISTINCT order_id) AS order_volume
FROM online_sales_large
GROUP BY year, month
ORDER BY year, month;
"""
result = pd.read_sql_query(query, conn)
result

query_top3 = """
SELECT
    STRFTIME('%Y-%m', order_date) AS month_year,
    SUM(amount) AS monthly_revenue
FROM online_sales_large
GROUP BY month_year
ORDER BY monthly_revenue DESC
LIMIT 3;
"""
top3 = pd.read_sql_query(query_top3, conn)
top3

